version: '{build}'
shallow_clone: true

environment:
  matrix:
    - perl_type: strawberry
    - perl_type: cygwin

install:
  - 'call .appveyor.cmd perl_setup'
  - '%perl% -V'
  - '%cpanm% --showdeps --with-develop --with-recommends --with-configure .'
  - '%cpanm% --installdeps -n --with-develop --with-recommends --with-configure .'

build: off

test_script:
  - '%perl% Makefile.PL'
  - '%make%'
  - '%make% test'
